name: Cypress CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    name: Ejecutar Tests de Cypress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ejecutar Cypress
        uses: cypress-io/github-action@v6
        with:
          install-command: 'npm install'
